version: "3.8"
services:
  proxy-db:
    image: "jc21/mariadb-aria:latest"
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - ${PROXY_DB_PORT}:${PROXY_DB_PORT}
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${PROXY_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${PROXY_DATABASE}
      MYSQL_USER: ${PROXY_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${PROXY_DB_PASSWORD}
      MARIADB_AUTO_UPGRADE: "1"
      MYSQL_TCP_PORT: ${PROXY_DB_PORT}
    volumes:
      - ./volumes/proxy/mysql/:/var/lib/mysql
  proxy:
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - "80:80" # Public HTTP Port
      - "443:443" # Public HTTPS Port
      - "81:81" # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "proxy-db"
      DB_MYSQL_PORT: ${PROXY_DB_PORT}
      DB_MYSQL_USER: ${PROXY_DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${PROXY_DB_PASSWORD}
      DB_MYSQL_NAME: ${PROXY_DATABASE}
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./volumes/proxy/data:/data
      - ./volumes/proxy/letsencrypt:/etc/letsencrypt
    depends_on:
      - proxy-db
  mysql:
    image: mariadb:latest
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
        "--innodb_file_per_table=ON",
      ]
    volumes:
      - ./volumes/mysql/mysqlconf:/etc/mysql/conf.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
  playsms:
    build: .
    volumes:
      - ./.env:/var/www/.env
      - ./volumes/playsms/html:/var/www/html
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 80:80
    environment:
      - TZ
      - ADMINPASSWORD
      - DBUSER
      - DBPASS
      - DBNAME
      - DBHOST
      - DBPORT
      - URLWEB
      - PATHWEB
      - PATHBIN
      - PATHLOG
      - PATHSTR
      - PATHSRC
      - PLAYSMS_WEB
      - XDEBUG_CONFIG
      - DB_ROOT_PASSWORD
    depends_on:
      - mysql
