version: "3.8"
services:
  mysql:
    image: mariadb:latest
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
        "--innodb_file_per_table=ON"
      ]
    volumes:
      - ./volumes/mysql/mysqlconf:/etc/mysql/conf.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MYSQL_TCP_PORT: ${DB_PORT}
  playsms:
    build: .
    volumes:
      - ./.env:/var/www/.env
      - ./volumes/playsms/html:/var/www/html
    ports:
      - 80:80
    environment:
      - TZ
      - ADMINPASSWORD
      - DBUSER
      - DBPASS
      - DBNAME
      - DBHOST
      - DBPORT
      - URLWEB
      - PATHWEB
      - PATHBIN
      - PATHLOG
      - PATHSTR
      - PATHSRC
      - PLAYSMS_WEB
      - XDEBUG_CONFIG
      - DB_ROOT_PASSWORD
    depends_on:
      - mysql
